### ISSUE TITLE
What about brownfield sites?

### ISSUE THREAD

**Issue by JulianOxley** [Appdynamics/ConfigMyApp#31]
Howdy Israel,

Thank you for this its exactly what I am looking for. I have inherited a large(ish) deployment of APM Java agents (746) in 70 applications across two controllers. DEXTER is telling me applications have grown to, in some cases, over 6000 SEPs and 200+ BTs.  To get this estate under control I foresee I need to undertake a load of tasks starting with the following;

Global
1. Tiers & Nodes > Delete All Tiers without performance data for 2 weeks
2. Configuration > Instrumentation > Scopes > Create a Scope for each Tier in the Application
3. App Server Agent Configuration > For each Application create Agent Properties for 'always-add-eum-metadata-in-http-headers' BOO True, 'enable-async2-eum-context-lookup' BOO True

For SEPs
1. Configuration > Instrumentation > Service Endpoints > Automatic Service Endpoint Detection > Disable all Automatic Service Endpoint Detection
2. Configuration > Instrumentation > Service Endpoints > Automatic Service Endpoint Detection > Servlet > Configure Naming > Use the first 1 segment
3. Configuration > Instrumentation > Service Endpoints > Custom Service Endpoints > For each Tier create a Servlet Exclude Transactions Rule using URI Is in List "/info, /health, /api-docs, /error"
4. Delete all other SEPs

<img width="540" alt="NonPro" src="https://user-images.githubusercontent.com/54266556/89884856-07401500-dbc2-11ea-8a60-16489f7a3bd9.png">

**Comment by iogbole** [comment]
Hey @JulianOxley and thanks for reaching out? What's your ask in the context of ConfigMyApp?

**Comment by JulianOxley** [comment]
> Hey @JulianOxley and thanks for reaching out? What's your ask in the context of ConfigMyApp?

Hi!, I think your app is targeting greenfield deployments, my point (badly made perhaps) was to automate cleaning up of brownfield deploys by deleting spurious SEPs, BTs Etc and pushing configuration per the steps above. Can you extend your app to do that?

**Comment by iogbole** [comment]
Hi @JulianOxley , you're correct, our initial focus is to enable faster rollout of AppD via CI/CD pipelines. That said, most of your "brownfield" use cases does fit into the tool's overall purpose. Let's break it down: 

Global

1.  Tiers & Nodes > Delete All Tiers without performance data for 2 weeks

I'd suggest you mark non-reporting nodes as historical instead of deleting the tiers.  The controller will automatically purge historical nodes after `720` hours and will preserve aggregated data at the tier level. 

Please refer to this solution for more details - https://github.com/Appdynamics/mark-nodes-historical

2.  Configuration > Instrumentation > Scopes > Create a Scope for each Tier in the Application

We have added this to our backlog. Thank you.  FYI @AlexJov .

3. App Server Agent Configuration > For each Application create Agent Properties for 'always-add-eum-metadata-in-http- 
    headers' BOO True, 'enable-async2-eum-context-lookup' BOO True

AppDynamics doesn't have a supported API to create agent properties. Please file a support ticket if this is absolutely required.

For SEPs

There are no officially supported APIs for SEPs too. 

ConfigMyApp is a wrapper for ONLY the officially supported APIs. We decided to stay away from non-documented APIs for obvious reasons.

**Comment by iogbole** [comment]
[CustomDashboard_vanilla.txt](https://github.com/Appdynamics/ConfigMyApp/files/5189034/CustomDashboard_vanilla.txt)
